"""OCR processing constants shared across modules."""

# Line merging thresholds
_MERGE_GAP_THRESHOLD_MULTIPLIER = 1.8
_MERGE_GAP_THRESHOLD_RATIO = 0.025
_MERGE_Y_THRESHOLD_MULTIPLIER = 0.70
_MERGE_Y_THRESHOLD_RATIO = 0.006

# Band grouping thresholds
_BAND_X_GAP_THRESHOLD_RATIO = 0.04
_BAND_X_GAP_THRESHOLD_HEIGHT_MULTIPLIER = 6.0
_BAND_CLOSE_Y_THRESHOLD_MULTIPLIER = 0.55
_BAND_OVERLAP_THRESHOLD_MULTIPLIER = 0.35
