"""OCR processing constants shared across modules."""

# Line merging thresholds
_MERGE_GAP_THRESHOLD_MULTIPLIER = 1.8
_MERGE_GAP_THRESHOLD_RATIO = 0.025
_MERGE_Y_THRESHOLD_MULTIPLIER = 0.70
_MERGE_Y_THRESHOLD_RATIO = 0.006

# Band grouping thresholds
_BAND_X_GAP_THRESHOLD_RATIO = 0.04
_BAND_X_GAP_THRESHOLD_HEIGHT_MULTIPLIER = 6.0
_BAND_CLOSE_Y_THRESHOLD_MULTIPLIER = 0.55
_BAND_OVERLAP_THRESHOLD_MULTIPLIER = 0.35

# Layout model timeouts (seconds)
_LAYOUT_MODEL_INIT_TIMEOUT_S = 30.0
_LAYOUT_MODEL_PREDICT_TIMEOUT_S = 45.0

# Layout block OCR tuning
_LAYOUT_BLOCK_MAX_CONCURRENCY = 1
_LAYOUT_BLOCK_PROGRESS_LOG_INTERVAL_S = 10.0
_LAYOUT_BLOCK_REQUEST_TIMEOUT_S = 40.0
_LAYOUT_BLOCK_RETRY_ON_TIMEOUT = True
_LAYOUT_BLOCK_LOW_COVERAGE_THRESHOLD = 0.30
